version: 2
jobs:
  test:
    docker:
      - image: circleci/node:12.10
    working_directory: ~/repo
    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "yarn.lock" }}
            - v1-dependencies-
      - run: yarn install
      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "yarn.lock" }}
      - run: yarn test

  build:
    docker:
      - image: circleci/node:12.10
    working_directory: ~/repo
    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "yarn.lock" }}
            - v1-dependencies-
      - run: yarn build
      - run: mkdir workspace && cp ./build ./workspace/
      - persist_to_workspace:
          root: workspace
          paths:
            - build

  plan_deployment:
    docker:
      - image: hashicorp/terraform:light
    working_directory: ~/repo
    steps:
      - checkout
      - attach_workspace:
          at: workspace
      - run: cp workspace/build build
      - run: terraform init
      - run: terraform plan -out terraform.tfstate
      - run: mkdir workspace && cp terraform.tfstate workspace/terraform.tfstate

workflows:
  version: 2
  ci:
    jobs:
      - test
      - build:
          requires:
            - test
          filters:
            branches:
              only: master
      - plan_deployment:
          requires:
            - test
            - build
          filters:
            branches:
              only: master
